### ISSUE TITLE
Follow XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by 0xSteeW** [normen/whatscli#1]
Hello, would like to suggest, as for tyding things up, to store whatscli.session in $HOME/.config or $XDG_CONFIG_HOME instead of $HOME, to declutter the home directory and follow the standard.

**Comment by normen** [comment]
Well why do you think I mention the fact that it currently stores its config files in the home dir? 🙂

Am 18.11.2020 02:29 schrieb Daniel Pérez:

**Comment by 0xSteeW** [comment]
Did not read that 😅 , sorry
