### ISSUE TITLE
How do i fix this? version : 1.0.10

### ISSUE THREAD

**Issue by apoorvapendse** [normen/whatscli#104]
![image](https://github.com/normen/whatscli/assets/102853901/3e2173d8-2004-4511-83fe-9f62e83e548f)

**Comment by TheBdouilleur** [comment]
Same problem here on Arch, installed AUR package whatscli 1.0.11-1

**Comment by TheBdouilleur** [comment]
Seems like a common and unsolved problem.
See #72
