### ISSUE TITLE
Document Phone Requirement (Required or not?)

### ISSUE THREAD

**Issue by maltfield** [normen/whatscli#113]
This issue is an attempt to address the obvious question: does this `whatscli` serve as an *alternative* to the WhatsApp app (ie: "is it a standalone desktop app?") or is it just yet-another-second-class-desktop-client that routes messages through the phone on the intranet?

### Solution

This is not a support request. This is a ticket to update the documentation. Please do *not* answer this question just on this GitHub issue.

The solution to this ticket should be to state, very clearly, in the `README.md` file if:

1. Using `whatscli` still requires the user to first install and create an account in the official WhatsApp app, and all messages are routed through the phone (eg like whatsapp web), or
2. Using `whatscli` still requires the user to first install and create an account in the official WhatsApp app, but afterwords WhatsApp can be uninstalled forever, and the desktop client can replace it (eg like Telegram), or
3. Using `whatscli` is an entirely first-class desktop app. You can create an account in it directly, and you never need to use the official WhatsApp mobile app for any reason (eg like Wire)

Again, please add this information to the `README.md` file -- not to this ticket.

**Comment by normen** [comment]
The readme contains info about the phone requirement.

**Comment by maltfield** [comment]
Sorry, why was this closed?

I just re-read the readme again, but I don't see where it says that the phone is a requirement?

**Comment by maltfield** [comment]
To clarify, apps like SimpleX allow you to sync chats with your phone, but it's optional.

Your readme states that you can scan a QR code to connect to whatsapp, but I can't find anywhere that it states that this is required, and that it will NOT function unless you first setup an account in the whatsapp app on your phone?

**Comment by normen** [comment]
> Sorry, why was this closed?
> 
> I just re-read the readme again, but I don't see where it says that the phone is a requirement?

https://github.com/normen/whatscli/blob/9854f579b759be50d3d2188d46a2deff87d6be6c/README.md?plain=1#L47

**Comment by maltfield** [comment]
Hi @normen the line you quoted does not address this issue. What it does make clear is that:

 * you need to have WhatsApp installed on a phone when you first start using this app

But it remains unclear:

1. Does whatscli still requires the user to have whatsapp after first installing? Can they uninstall whatsapp from their phone forever after first scanning the QR code?
2. Does whatscli send messages when the phone is dead, or does it need to route the messages through the phone (eg like "whatsapp web") or does it send the messages independently (eg like "beeper")?

Please re-open this issue to address these questions in the README

**Comment by normen** [comment]
No

**Comment by maltfield** [comment]
Would you be open to a PR to address this still-existing issue?

**Comment by maltfield** [comment]
>  I doubt that this version of whatscli is working in any country anymore

Should I open another ticket to address this too? Sounds like the `README` needs a few updates...

**Comment by maltfield** [comment]
> The doc clearly states that the web app API is used.

I don't know what that means. Lots of users don't know what an API is, and they definitely don't know what some specific "web app API" is used for, and the ramifications of that.

Documentation should be written for all end-users, not just for developers.
