### ISSUE TITLE
MacOS First launch error

### ISSUE THREAD

**Issue by p-i-c-o** [normen/whatscli#115]
The main UI flashes then dissapears and this error shows up:

<img width="1323" alt="Screenshot 2024-09-02 at 3 22 28 PM" src="https://github.com/user-attachments/assets/00e0d2b2-5339-4cad-b0a1-f6e2259c8716">

**Comment by normen** [comment]
<img width="579" alt="Readme-screen jpeg" src="https://github.com/user-attachments/assets/f4187cc8-d2f2-4a51-80a5-442510860e05">
