### ISSUE TITLE
runtime error invalid memory addres

### ISSUE THREAD

**Issue by teraluis** [normen/whatscli#116]
I installed the application via brew and when I launch it with the whatsappcli command I get this error:

"runtime error invalid memory addres or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 adr=0x0pc] "

**Comment by madmedicnl** [comment]
Getting the same error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x28 pc=0xbac0da]

Installed with Go install on windows Powershell preview

**Comment by mmonseurs** [comment]
Same here, running the Linux executable on Debian.

[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f2e1f]
