### ISSUE TITLE
[Error] invalid string with tag 174

### ISSUE THREAD

**Issue by har5ha** [normen/whatscli#15]
Installed the latest version [v0.6.8]

When whatscli autoconnects  on launch, it only downloads the phone nos. under contacts. Then when I use /connect to reconnect.. It adds/downloads Names under the Contacts and thows the following error.

`error processing data: error decoding binary: could not decode binary: invalid string with tag 174`

Also Under WhatsApp Groups ... my friends names do not show up .

Thanks for your help!

**Comment by normen** [comment]
Hm, no idea. Sounds like go-whatsapp doesn't like one of your contacts and thus fails to fill its database with the contact info.
By "throws" do you mean the app actually crashes and shows a stack trace? Or does it print red text in the chat view?

Am 20.11.2020 04:26 schrieb har5ha:

**Comment by har5ha** [comment]
The latter, it prints the error in red text in the chat view. But the app doesn't crash though.

**Comment by normen** [comment]
yeah, that means that the go-whatsapp library reported an error with the data.. you could check over at their projects issue tracker if this issue came up. then check back here so we can see if we find a workaround.

Am 20.11.2020 04:37 schrieb har5ha:

**Comment by normen** [comment]
0.6.9 adds a bit more info and problem-prevention, idk if it will affect this issue..

**Comment by normen** [comment]
Still getting that same error? Check out this thread: https://github.com/Rhymen/go-whatsapp/issues/187

**Comment by normen** [comment]
Closing this, the conversation should continue in the referenced thread if possible.
