### ISSUE TITLE
When trying to connect I get "restoring failed: admin login responded with 401"

### ISSUE THREAD

**Issue by etlon** [normen/whatscli#17]
Newest version v0.6.9, any idea? Already did a fresh install, but it is still not working

**Comment by normen** [comment]
Maybe try deleting `$HOME/.whatsapp.session` and logging in via QR again.

**Comment by etlon** [comment]
Sadly there is no .whatsapp.session file in the home folder on my arch linux.

**Comment by normen** [comment]
No idea then, your login attempt seems to fail at the server level. What exactly are you doing anyway? Can you make a proper report please, like "To reproduce do...".
Like does it happen right when you start the app? When you scan the code? And again, please don't just answer "when I start the app".

Am 20.11.2020 09:22 schrieb Cedric Nolte:

**Comment by normen** [comment]
oh sorry, ofc that would have been `.whatscli.session`

**Comment by etlon** [comment]
thanks! deleting the `.whatscli.session` file worked for me!
