### ISSUE TITLE
[Feature] URL selection / opening

### ISSUE THREAD

**Issue by normen** [normen/whatscli#19]
The app should allow selecting and opening URLs in the chat view, maybe through an external app like urlview or extract_url

**Comment by BachoSeven** [comment]
if you want something nicer than `urlview`, I suggest using [`urlscan`](https://github.com/firecat53/urlscan).

**Comment by normen** [comment]
The question is more if it should be an internal function of whatscli or if it should invoke an external tool which would be configurable. I.e. you could choose the command of your liking like in mutt, weechat etc.

The jp2a command will also be configurable in the future.

Am 22.11.2020 05:19 schrieb Francesco:

**Comment by normen** [comment]
I chose an internal method, you can now open urls by pressing "u" when selecting messages
