### ISSUE TITLE
[Feature] configuration

### ISSUE THREAD

**Issue by normen** [normen/whatscli#2]
The app should allow for some customization, especially for keyboard shortcuts, ui layout and ui colors.

It should also store its configuration, contact and session files in a proper location, i.e. `~/.config` on unix, `~/Library/Preferences` on macos and `~/AppData/Local` on windows.

For this a configuration management system should be added.

**Comment by BachoSeven** [comment]
Hi, [this](https://github.com/adrg/xdg) Go implementation of the XDG base directory specification might be helpful for this feature. The implementation is also cross-platform.

**Comment by normen** [comment]
Cool. Thanks. If you come across any such library for managing strings in a config file and/or key binding handling for tview I'm all ears.

**Comment by normen** [comment]
This go package does a lot of the things that are needed for this: https://github.com/go-ini/ini

**Comment by normen** [comment]
This one can handle tcell keys as strings: https://gitlab.com/tslocum/cbind

**Comment by normen** [comment]
implemented in 0.7.0

**Comment by BachoSeven** [comment]
Regarding this: I think that it would be better to store the `session` file in $XDG_DATA_HOME/whatscli, rather than $XDG_CONFIG_HOME/whatscli, as it's a binary and falls better in the "data" category, since it does not store user preferences.

For this, I think it should be enough to change `xdg.ConfigFile("whatscli/session")` to `xdg.DataFile("whatscli/session")` at line [165](https://github.com/normen/whatscli/blob/master/config/settings.go#L165) of `settings.go`. I hope that makes sense

**Comment by normen** [comment]
Mh, yeah but I guess the file should be somewhat easily accessible (i.e. in a directory the user expects) so its easy to sync (I am using whatscli on multiple computers with one login). Thats why I put it in the settings folder..

**Comment by BachoSeven** [comment]
I see, so it's actually a feature to be able to sync that file. I suppose that also makes sense if it works using the same session file, didn't think it could be used like that. Thanks!

**Comment by normen** [comment]
>I see, so it's actually a feature to be able to sync that file. I suppose that also makes sense if it works using the same session file, didn't think it could be used like that. Thanks!
I'm not sure if it would make more sense to simply register multiple web clients in your phone though. Its just how I started using it.

Theres another thing about this configuration setup that can be improved though - documenting this here as I just thought about it. Actually the library for finding the path supports searching all possible paths (e.g. .config/whatscli .whatscli/ or simply a .whatscli in root) and reporting the found one. I should use that as right now I just ask for the "optimal" path and use that. I guess especially when moving around files between computers the optimal path can sometimes not be used.
