### ISSUE TITLE
config of colors for the input field

### ISSUE THREAD

**Issue by kguidonimartins** [normen/whatscli#20]
@normen, thanks for this application. It's improved my workflow a lot!

There is a way to adjust both background and foreground of the input field? I think the contrast of the bg blue (color-blind here) e fg white is really hard at least for my needs.

Thanks again

**Comment by normen** [comment]
I actually set the foreground and background colors for the text input, idk exactly why it doesn't get picked up. I guess tview styles text inputs by default somehow? Maybe you can investigate too as I am working on new features in the time I have for this software.

Thanks for the input!

Am 22.11.2020 05:54 schrieb Karlo Guidoni Martins:

**Comment by normen** [comment]
Actually found the issue, 0.7.3 is on the way.

**Comment by normen** [comment]
Sorry, I conflated two things here. I talked about a bug in the input color settings, you wanted to be able to set separate colors. v0.7.4 allows that now. Start the app once to see the new color options in the config.

**Comment by kguidonimartins** [comment]
I was trying to find out why it wasn't working. But now it’s perfect. Thank you so much for your time!
