### ISSUE TITLE
Panic runtime error when typing command beginning by whitespace

### ISSUE THREAD

**Issue by Quentinchampenois** [normen/whatscli#26]
Hi, first of all thanks for your work, I am still trying to understand how to connect but it is interesting

#### Bug description

I have noticed by mistake that when user type a whitespace before the command, the program panic because of `invalid memory address or nil pointer dereference`. 
I can reproduce this bug several times, I think the bug is related to the scroll. 

#### How to reproduce

* Execute program
* Enter : ` /help`, beginning with whitespace
* Then scroll up
* See error 

#### Environment 
* WhatsCLI `v1.0.5` ( based on `master` branch)
* MacOS Catalina : v 10.15.6

#### Stacktrace
I apologize I did not found a log file for the complete error, I just have a screenshot .. 

<img width="1440" alt="Screenshot 2020-12-05 at 13 09 44" src="https://user-images.githubusercontent.com/26109239/101242809-1b24ff00-36fc-11eb-9d6d-0de39eccec83.png">

#### Additional context

I remain available if you need more information.

**Comment by normen** [comment]
Right, thats very possible.

**Comment by normen** [comment]
I guess this is when you have no chat selected and you are offline?

**Comment by Quentinchampenois** [comment]
Yes you are right, I have no chat and seems to be offline (following the screenshot in description) 
Sorry for the answer delay !

**Comment by normen** [comment]
Okay, does the latest version 1.0.5 fix that? It should. And to connect you need to scan the QR code with your WhatsApp on your phone - I added some documentation to the README

**Comment by Quentinchampenois** [comment]
Yes it is fixed, 
I have also seen the documentation, thank you !
