### ISSUE TITLE
Count unread messages outside the UI

### ISSUE THREAD

**Issue by kguidonimartins** [normen/whatscli#27]
Hi @normen, thanks for this program. It is very useful!

I would like to integrate your program into my system and generate notifications about unread messages. I usually use notify-send or some shell script to display information on my statusbar. My idea is to use cron to connect, count unread messages and generate a notification with the number of unread messages. I already use this for emails, for example.

![pic-selected-201208-1203-12](https://user-images.githubusercontent.com/8163542/101501003-f3c57080-394d-11eb-82cf-677388f6b792.png)

Is there a way to do this with your program?

I don't know go, and I already messed up all my clone of your repository. Feel free to ignore my message if nothing I’m saying here makes sense.

Thanks again!

**Comment by normen** [comment]
Idk, don't the desktop messages accumulate somewhere on your OS as an external indicator?

**Comment by normen** [comment]
Realizing I didn't document this at all except in the release where it was added - just set `enable_notifications = true` in your config.

**Comment by kguidonimartins** [comment]
> Idk, don't the desktop messages accumulate somewhere on your OS as an external indicator?

I haven't figured that out yet.

> Realizing I didn't document this at all except in the release where it was added - just set `enable_notifications = true` in your config.

Notifications work perfectly at all. But it would be interesting to have access only to the number of unread messages outside the UI. I'll mess up your code a little bit more to find out.

Thank's for your time.

**Comment by normen** [comment]
Really I want to avoid this app becoming too much of a "bridge" or "gateway" to WhatsApp. Thats why I also don't want to add command line options to directly send messages etc. It should be clear that this is an UI for WhatsApp, not a (possible) spam bot. Sure, reading the unread messages from the live app wouldn't be much of an issue but it would already go in the "wrong" direction. Anyway, if you find a nice way to add this hit me.

**Comment by kguidonimartins** [comment]
I totally agree with you. Especially because of the last few years that WhatsApp has been used as a campaign tool, at least in my country.

> if you find a nice way to add this hit me.

Sure! :)
