### ISSUE TITLE
V1.05 panic: runtime error

### ISSUE THREAD

**Issue by Masacaai** [normen/whatscli#30]
Hello, I've downloaded the latest release v1.05 from Github onto my Arch Linux system and followed the instructions given to install and run the program. However, I'm met with this error in the terminal:

`panic: runtime error: invalid memory address or nil pointer dereference
                                                                       [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8a4c60]
               
               goroutine 39 [running]:
                                      github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0xc0003022a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                  	/Users/normenhansen/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1/session.go:191 +0x80
                                                                                                                 github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0000d1a20, 0x0, 0x0, 0x0)
                                                                                        	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:234 +0x12a
                                               github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0000d1a20, 0xc00020a0d0, 0xc000218020)
                          	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:71 +0x65
                                                                                                            created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
                                                          	/Users/normenhansen/Dev/GoCode/whatscli/messages/session_manager.go:65 +0x95
`

I received the error in this exact same formatting. As I'm not familiar with the Go language, I wasn't able to make head-nor-tails of it. I hope you'd be able to help me sort out this issue.

I have go-2:1.15.6-1 installed from the Arch repositories and I'm using the urxvt terminal.
Please let me know if I need to provide any additional details. Thanks for your cooperation!

**Comment by Masacaai** [comment]
Nevermind, the AUR version works..., I'm sorry for opening the issue hastily

**Comment by JunyaoC** [comment]
Hey may i know \how do you resolve this?
