### ISSUE TITLE
[Feature Request] To be able to manually set names for contacts that dont have a public display name

### ISSUE THREAD

**Issue by Masacaai** [normen/whatscli#34]
I'm not familiar with Go so I'm not sure how hard this would be to implement, but it would be nice if the user was able to set names for the contacts that don't have public display names set.

**Comment by normen** [comment]
You can just make a contact on your phone.

**Comment by Masacaai** [comment]
I'm sorry for reopening this issue, but I'm confused and I'm hoping you can clear it
All the people whose names aren't shown on whatsCLI are already saved under names on my contacts list on my phone.

**Comment by normen** [comment]
...and WhatsApp has access to those?

**Comment by Masacaai** [comment]
Yeah it does. Most of the contacts on my phone were created FROM Whatsapp's 'create contact' feature

**Comment by normen** [comment]
Can you please select one of those messages (`Ctrl-w`) and then press `i`, then post the output here.

**Comment by Masacaai** [comment]
Okay, I did what you asked and this is the output I got:

(I've redacted the RemoteJid for all pictures here)

![grpchati(mod)](https://user-images.githubusercontent.com/59050442/103159447-ef6cd480-47e2-11eb-9e16-0c1a58d75b28.jpg)

I was intrigued so I also performed the same thing on a non-group chat:

![2020-12-27-010817_1064x178_scrot](https://user-images.githubusercontent.com/59050442/103159313-5e492e00-47e1-11eb-8681-bb7585ac5ecc.png)

![dmi(mod)](https://user-images.githubusercontent.com/59050442/103159451-fa276980-47e2-11eb-97c5-9346ce0c6fa5.jpg)

Other than ID and RemoteJid, most of the other messages show nothing when the message info is requested.

A few messages were able to show Participant and QuotedMessageID but these were few and far in between.

**Comment by normen** [comment]
Hm, not much I can do there, I guess you tried reconnecting/restarting the app already. That would definitely load the latest address book again.

I'd rather not add any internal address book as the feature really should be working from the go-whatsapp side. I just removed the old feature creep that did exactly that. Maybe check their issue tracker about similar issues.

**Comment by Masacaai** [comment]
Oh well, thank you anyway! I'll comb through go-whatsapp's issue tracker later. For now, I'll just have to view group chats from my phone.
