### ISSUE TITLE
Opening images with ApolloOne doesn't work: Make open image command customisable?

### ISSUE THREAD

**Issue by crstnbr** [normen/whatscli#35]
First of all, great project, thanks for maintaining it.

I noticed that when I try to open a, say, jpeg image in a message (`o`) it does work as expected when my default application for jpegs is `Preview` (I'm on macOS). If however I make [Apollo](https://www.apollooneapp.com) the default and press `o`, Apollo starts but then shows a popup saying "Image file not found". I assume that the command that `whatscli` sends out is somehow incompatible with Apollo.

It would be great if the command triggered by `o` would be customisable in the config file. The path to the file would ideally be a template parameter, say `{PATH}` such that I could write something like
```
open_image = /my/favorate/app -a-parameter-it-needs {PATH}
```

Unfortunately I don't know much Go, otherwise I would try to implement it myself. Nonetheless, if you are short on time, pointers to how/where to integrate this feature would be appreciated as well.

Best regards!

**Comment by normen** [comment]
I guess its due to spaces in the file name.

**Comment by crstnbr** [comment]
Hm, I don't think so. If I press `d` and check the path it doesn't contain any spaces.

**Comment by normen** [comment]
Can you open files from the command line with Apollo at all? Try "open /path/to/my/file.jpg" in the command line. I don't think the problem is in whatscli.
