### ISSUE TITLE
notifications via terminal bell

### ISSUE THREAD

**Issue by keegancsmith** [normen/whatscli#36]
Rather than using the `beeep` library, you could introduce notifications via the terminal just using the classic "bell". Is there any interest for me contributing this? EG via a configuration, or just always doing beep? For example I use this patched version of whatscli to achieve that:

```diff
diff --git a/messages/session_manager.go b/messages/session_manager.go
index 1c7cdf6..9b62fb6 100644
--- a/messages/session_manager.go
+++ b/messages/session_manager.go
@@ -16,7 +16,6 @@ import (
 	"github.com/Rhymen/go-whatsapp"
 	"github.com/gabriel-vasile/mimetype"
 	"github.com/gdamore/tcell/v2"
-	"github.com/gen2brain/beeep"
 	"github.com/normen/whatscli/config"
 	"github.com/normen/whatscli/qrcode"
 	"github.com/rivo/tview"
@@ -89,8 +88,8 @@ func (sm *SessionManager) runManager() error {
 				if int64(msg.Info.Timestamp) > time.Now().Unix()-30 {
 					if int64(msg.Info.Timestamp) > sm.lastSent.Unix()+config.Config.General.NotificationTimeout {
 						sm.db.NewUnreadChat(msg.Info.RemoteJid)
-						if config.Config.General.EnableNotifications && !msg.Info.FromMe {
-							err := beeep.Notify(sm.db.GetIdShort(msg.Info.RemoteJid), msg.Text, "")
+						if !msg.Info.FromMe {
+							_, err := fmt.Printf("\a")
 							if err != nil {
 								sm.uiHandler.PrintError(err)
 							}
@@ -101,8 +100,8 @@ func (sm *SessionManager) runManager() error {
 				// notify if message is younger than 30 sec and not in focus
 				if int64(msg.Info.Timestamp) > time.Now().Unix()-30 {
 					sm.db.NewUnreadChat(msg.Info.RemoteJid)
-					if config.Config.General.EnableNotifications && !msg.Info.FromMe {
-						err := beeep.Notify(sm.db.GetIdShort(msg.Info.RemoteJid), msg.Text, "")
+					if !msg.Info.FromMe {
+						_, err := fmt.Printf("\a")
 						if err != nil {
 							sm.uiHandler.PrintError(err)
 						}
```

**Comment by normen** [comment]
I think I the source even includes the commented out bell, doesn't it? At least I used that when I tested. Otherwise, I really only know of people who _disable_ the terminal bell. Its annoying, all apps share it and it can mean like pretty much everything when your terminal goes "beep". So I never really considered it a real option 🙂 But idk, if it was made optional though the settings, why not?

**Comment by keegancsmith** [comment]
> I think I the source even includes the commented out bell, 
> doesn't it?

Aah, I didn't explore the source that deeply. I just looked at 
uses of beeep :)

> Otherwise, I really only know of people who _disable_ the 
> terminal bell.

Agreed, bell can be annoying. However, I find it less annoying 
that visually loud notifications :) But I personally use the 
visual bell just so I know which tabs (in kitty) have a 
notification. So I find it useful.

> But idk, if it was made optional though the settings, why not?

Happy to implement this if you like? How about `EnableBell`?

**Comment by normen** [comment]
Sure, let's call it `UseTerminalBell` though, default `false` 🙂 The toggle should still be `EnableNotifications` which then uses Beep or Bell depending on the state of `UseTerminalBell`.
