### ISSUE TITLE
QR code too big

### ISSUE THREAD

**Issue by BankruptAce5** [normen/whatscli#40]
Hi, just wanted to say thanks for creating this minimalist client, love it, the only issue is, I am not really able to connect to it because the QR code it prints on my screen is too big to be scanned by my phone, i.e. it goes outside of the bounds of the window.

**Comment by BankruptAce5** [comment]
![2021-03-11-001445_1360x768_scrot](https://user-images.githubusercontent.com/80431128/110710820-d333dd80-81fe-11eb-827e-59d2f7328cf5.png)

**Comment by normen** [comment]
Just reduce the font size..
