### ISSUE TITLE
QR code not working

### ISSUE THREAD

**Issue by AlbertoTrigo** [normen/whatscli#41]
When trying to scan the whole QR code, it isn't detected by whatsapp web.

**Comment by normen** [comment]
Does "trying to scan" imply that you _don't_ scan the whole code?

**Comment by AlbertoTrigo** [comment]
> Does "trying to scan" imply that you _don't_ scan the whole code?

No, it means that while scanning the whole code, the phone doesn't respond. (i.e: isn't detected as a functional QR code)

**Comment by johnescobia** [comment]
@AlbertoTrigo I had a similar issue. It's fixed by making sure the full QR code is on display. Somehow the QR code isn't displayed fully by default. I had to drag the terminal and enlarge it to the right to show the full QR code.  Hope it helps!

**Comment by AlbertoTrigo** [comment]
> @AlbertoTrigo I had a similar issue. It's fixed by making sure the full QR code is on display. Somehow the QR code isn't displayed fully by default. I had to drag the terminal and enlarge it to the right to show the full QR code. Hope it helps!

Yeah, I have already tried that a few times. Thanks for the help though. Here is a screenshot of it 
![pic-window-210425-1849-51](https://user-images.githubusercontent.com/76629093/116001902-4189ff00-a5f7-11eb-9f68-eb5619e287f7.png)

**Comment by normen** [comment]
Maybe try changing the font/terminal settings? It looks like your display is inverted compared to what I see when I start whatscli.

**Comment by AlbertoTrigo** [comment]
Well, I finally got it. Just had to change the terminal color-scheme to a dark one. Thanks for everyone who helped. I guess I can close this issue now.

**Comment by HaroonRehman** [comment]
I am not be able to connect. Terminal Response Abnormally. When the **release.sh** was running I stopped it quit a few time after that I think the script was not be able to download the packages in a right way. Please if this thing causing me a issue guide me how can I perform a clean install again.

**Comment by HaroonRehman** [comment]
> 

I thought that it is a installing script.

Now tell me the fix. I am crazy about running WhatsApp in Terminal .

**Comment by normen** [comment]
> Now tell me the fix. I am crazy about running WhatsApp in Terminal .

If you tell me how long the piece of string I am holding in my hand is I will.

**Comment by HaroonRehman** [comment]
Awwwwww Can't wait to run WhatsApp in Terminal.

FIIIIIXXXX iTTTTTTTT
