### ISSUE TITLE
Group member names aren't visible in some countries

### ISSUE THREAD

**Issue by theEndurance-del** [normen/whatscli#43]
I recently started using whatscli and it works great for one to one chat(or personal chats) but on group chats don't show even the public names for users(or the names saved in my contact list) as you can see here.
![Screenshot from 2021-04-27 14-25-32](https://user-images.githubusercontent.com/57960301/116214688-91d29f80-a764-11eb-9c62-7453677eb735.png)
This is the screenshot of the exact same message from a mobile device using native whatsapp application on a smartphone.
![Screenshot2](https://user-images.githubusercontent.com/57960301/116216202-ffcb9680-a765-11eb-820f-3418958e67a9.jpg)

I am using `whatscli 1.0.7-1`
OS: `Arch linux`
Kernel: `5.11.16-zen1-1-zen`
Installed via: AUR
Installed the `whatscli` instead of `whatscli-git`

I dearly request to look into this issue since it was reported once before by another user @masacaai

**Comment by normen** [comment]
I still can't reproduce this issue, group names show up properly for me, no matter if the users are in my contacts or not. Without the issue occurring its impossible to look into.

**Comment by theEndurance-del** [comment]
Sure, I get it. I would once also try building this from source so just to check whether the issue was the package manager not installing dependencies properly or something else.

**Comment by normen** [comment]
I run whatscli on MacOS (two different versions), Windows (v10) and Linux (two platforms, three versions).

Go applications in general have no libraries, everything is in the binary.

**Comment by theEndurance-del** [comment]
Well if the client is running properly on different distributions of linux itself then apparently the issue cannot be with the OS since at binary level most codes should run similarly with the OS, So my guess would be that it is a issue occurring during loading of the application or how it makes connection to the back end.

I have attached the information of a group message which may help you:
![whatscliissue](https://user-images.githubusercontent.com/57960301/116431225-376d3800-a865-11eb-8700-2c8c7131c72f.png)

As you can notice unlike  [this](https://github.com/normen/whatscli/issues/34) issue reported by @mascaai I can actually see the participant ID and as it was stated there I rather am able to see the participant ID for all messages, also I am trying to navigate through go-whatsapp issues but till now I have had no success.

**Comment by normen** [comment]
No idea, another thing to try would be using the binary from the release page here on github instead of the AUR build, which is created by somebody else.

**Comment by theEndurance-del** [comment]
> No idea, another thing to try would be using the binary from the release page here on github instead of the AUR build, which is created by somebody else.

I downloaded the second time form the release page but the result didn't change... it still doesn't show names in groups

**Comment by theEndurance-del** [comment]
> I downloaded the second time form the release page but the result didn't change... it still doesn't show names in groups

May be I'll try downloading an older version and try running it I'll inform you if it works...

**Comment by normen** [comment]
Maybe we could/should track the country where this happens as well, maybe theres differences in what the WhatsApp server provides per country (or even mobile provider?). So for me I am in Germany with Vodafone and it works.

**Comment by theEndurance-del** [comment]
For me it is India, my ISP is Reliance Jio, and my DNS is cloudfare

**Comment by theEndurance-del** [comment]
> May be I'll try downloading an older version and try running it I'll inform you if it works...

Also I downloaded both v1.0.7 and v1.0.6 from the release pages but I got the same result

**Comment by theEndurance-del** [comment]
> Maybe we could/should track the country where this happens as well, maybe theres differences in what the WhatsApp server provides per country (or even mobile provider?). So for me I am in Germany with Vodafone and it works.

Also today I tried reconnecting to the server on the application and then this happened:
![image](https://user-images.githubusercontent.com/57960301/117756729-5e037980-b23c-11eb-9430-b287dffd3532.png)

**Comment by normen** [comment]
Could be that that "binary error" hints at an issue with reading your phonebook from the server for some reason. Thats not something thats done in this plugin though but in the go-whatsapp library.

**Comment by kavin25** [comment]
I'm from India, and am facing the same Issue

**Comment by theEndurance-del** [comment]
> I'm from India, and am facing the same Issue

I guess then this is in fact an issue with how the regional server is responding to the client.

**Comment by iamleot** [comment]
I had a similar problem but after WhatsCli 1.0.9 I can no longer reproduce it.
@theEndurance-del can you please recheck?

**Comment by theEndurance-del** [comment]
> I had a similar problem but after WhatsCli 1.0.9 release I can no longer reproduce it (probably related to the bump of go-whatsapp).
> 
> @theEndurance-del can you please recheck?

Can confirm. The issue no longer exists, I guess we can close the issue with this comment.

**Comment by iamleot** [comment]
Cool!  Thanks @theEndurance-del for the quick feedback!
