### ISSUE TITLE
More support for images

### ISSUE THREAD

**Issue by fdelucchijr** [normen/whatscli#44]
### Reason:
In my country (Peru), WhatsApp is the main used app for communication, even for the government. 
In this exchange of messages images is very important part of the conversation, obviously, like sending receipts or scanned documents, or products, etc.

### Request:
I would like to ask for more support into the WhatsApp images. The basic one is inline automatic preview (or the refinement of this. I'm in a M1 machine and have troubles using PIXterm or introducing commands in `whatscli.config`), but this can be much bigger and robust set of tools like preview of gifs or videos or allow sharing the foto using a vim's like "open_in:" command.

### Also:
I know this feature isn't an easy one. I'm learning Go in my free times just to contribute to this project that keep me so much interested! Any ideas of where to continue?

**Comment by normen** [comment]
You can set ANY application to open your images when you press "o" so I don't think theres need for any additional "support" here. Just set your default terminal apps properly.
