### ISSUE TITLE
video error: 

### ISSUE THREAD

**Issue by ALGBBSH** [normen/whatscli#48]
When I run:

Control + w
[VIDEO] + s

Error:

/data/data/com.termux/files/home/downloads/whatscli/messages/session_manager.go:145 +0xce4                                                                                                       created by github.com/normen/whatscli/messages.(*SessionManager).StartManager                                                                                                              /data/data/com.termux/files/home/downloads/whatscli/messages/session_manager.go:65 +0x84

My system don't have graphical environment. I would like to run a command like vlc by doing this.

**Comment by normen** [comment]
That won't work. `s` is for showing the image inline in the terminal. Just use `o` to open the file and assign the correct handling app in your OS.

**Comment by ALGBBSH** [comment]
When I run:

Control + w
[VIDEO] + o


Error:

/data/data/com.termux/files/home/downloads/whatscli/messages/session_manager.go:145 +0xce4                                                                                                       created by github.com/normen/whatscli/messages.(*SessionManager).StartManager                                                                                                              /data/data/com.termux/files/home/downloads/whatscli/messages/session_manager.go:65 +0x84

The same error.

**Comment by normen** [comment]
That error message is truncated, it doesn't tell me anything about what is actually going wrong.

**Comment by ALGBBSH** [comment]
This is error message complete, when select video and pulse _o_:


panic: runtime error: index out of range [0] with length 0

goroutine 56 [running]:
github.com/normen/whatscli/messages.(*SessionManager).downloadMessage(0x40001d9340, 0x40000a9c50, 0x14, 0x1, 0x0, 0x40000f2420, 0x1b, 0x1)
	/root/whatscli/messages/session_manager.go:798 +0xa6c
github.com/normen/whatscli/messages.(*SessionManager).execCommand(0x40001d9340, 0x5c7f7e, 0x4, 0x4001d02840, 0x1, 0x1)
	/root/whatscli/messages/session_manager.go:354 +0x28cc
github.com/normen/whatscli/messages.(*SessionManager).runManager(0x40001d9340, 0x4000278b40, 0x400027c0e0)
	/root/whatscli/messages/session_manager.go:145 +0xe4c
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
	/root/whatscli/messages/session_manager.go:65 +0x90

After this error, the program crash and close.

I don't know to find more information about the error. in any case, thanks for your help.

**Comment by normen** [comment]
Looks like for whatever reason the downloaded video is recognized as audio and returns no data.. Hard to say whats the issue there. I guess it's only with certain videos.

**Comment by ALGBBSH** [comment]
In my OS ( PosmarketOS -Alpine Linux), arquitecture ( arm64 ) and Kernel 5.12.12  this problem is in all videos. It is a problem the my system. I will try to discover the problem. Thank for your program and help.  Pleased to meet you.

**Comment by normen** [comment]
Can you download or open anything? Maybe the download path isn't writable? Check the settings for the path.

**Comment by ALGBBSH** [comment]
With Images all ok: dowload, open and show. All perfect.

However, video all crash: Download, open and show. When download video or open or show the program close with error.

I have tried this with user root:

/root/.config/whatscli/whatscli.conf:

[general]
download_path        = /Downloads                                     preview_path         = /Downloads                                     cmd_prefix           = /
show_command         = openvt -s fbi
enable_notifications = false                                          use_terminal_bell    = false
notification_timeout = 60                                             backlog_msg_quantity = 10

[keymap]                                                              switch_panels    = Tab
focus_messages   = Ctrl+w                                             focus_input      = Ctrl+Space
focus_chats      = Ctrl+e
copyuser         = Ctrl+c                                             pasteuser        = Ctrl+v
command_backlog  = Ctrl+b
command_read     = Ctrl+n                                             command_connect  = Ctrl+r                                             command_quit     = Ctrl+q
command_help     = Ctrl+?                                             message_download = d
message_open     = o
message_show     = s                                                  message_url      = u
message_info     = i
message_revoke   = r                                                  
[ui]                                                                  chat_sidebar_width = 30                                                                                                                     [colors]
background       = black                                              text             = white
forwarded_text   = purple                                             list_header      = yellow                                             list_contact     = green
list_group       = blue
chat_contact     = green                                              chat_me          = blue
borders          = white
input_background = blue                                               input_text       = white
unread_count     = yellow
positive         = green                                              negative         = red

Permision:

drwxrwxrwx    2 root     root          1024 Jul  9 00:18 Downloads

And Nothing, the same error:                                                        panic: runtime error: index out of range [0] with length 0

goroutine 40 [running]:                                                                                                                                github.com/normen/whatscli/messages.(*SessionManager).downloadMessage(0x40001db130, 0x4000935b60, 0x20, 0x0, 0x1, 0x0, 0x0, 0x0)
        /root/whatscli/messages/session_manager.go:798 +0xa6c                                                                                          github.com/normen/whatscli/messages.(*SessionManager).execCommand(0x40001db130, 0x5cd143, 0x8, 0x4000021220, 0x1, 0x1)
        /root/whatscli/messages/session_manager.go:344 +0x42ac
github.com/normen/whatscli/messages.(*SessionManager).runManager(0x40001db130, 0x4000270b60, 0x400027a0e0)
        /root/whatscli/messages/session_manager.go:145 +0xe4c
created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
        /root/whatscli/messages/session_manager.go:65 +0x90

**Comment by theEndurance-del** [comment]
> download_path = /Downloads
> preview_path = /Downloads

Hey, shouldn't these two locations be pointing towards `$HOME/Downloads`?? where `$HOME` is your home directory (`/home/user` in my case).

**Comment by ALGBBSH** [comment]
the video works for me. 

Solution1:

in directory whatsapi/messages

sed -i 797,799s#^#%%#g session_manager.go

Solution2:

nano session_manager.go

line 797-799 :

                      if exts, err := mime.ExtensionsByType(v.Type); err == nil {
                              fileName += exts[0]
                      }

switch for

//                      if exts, err := mime.ExtensionsByType(v.Type); err == nil {
//                              fileName += exts[0]
//                      }

Interestingly, the problem is solved.

**Comment by normen** [comment]
I see, maybe 1.0.10 fixes this then. Seems like the MIME-recognition goes wrong for some reason with your videos (whatever is different about them).
