### ISSUE TITLE
Crash after scanning QR

### ISSUE THREAD

**Issue by mark2185** [normen/whatscli#52]
I'm running the `whatscli` from `AUR` and it prompts me to scan the QR code.

Upon doing that it exits like this:

![image](https://user-images.githubusercontent.com/8365241/135576599-169bbf46-22e4-4359-aa20-ae26164ea0ae.png)

Is there a log or anything else I can provide?

**Comment by normen** [comment]
Seems like the response form the whatsapp servers is malformed, maybe thats due to the recent changes in whatsapp concerning multiple device logins.

**Comment by mark2185** [comment]
Well, I currently _am_ in the beta so that might have something to do with it.

**Comment by normen** [comment]
Maybe check upstream with the https://github.com/Rhymen/go-whatsapp library if they have issues/solutions surrounding that.

**Comment by normen** [comment]
Right, there: https://github.com/Rhymen/go-whatsapp/issues/601

**Comment by normen** [comment]
See #52
