### ISSUE TITLE
/upload failed?

### ISSUE THREAD

**Issue by kurokirasama** [normen/whatscli#54]
Hello,

I tried sending a file using `/upload` command, and the app crashed and now it doesn't connect.
![Screenshot from 2021-11-01 22-49-50](https://user-images.githubusercontent.com/5784951/139773669-9807bbb0-e427-465e-b4ca-e27f4ebbd995.png)
Regards,

**Comment by kurokirasama** [comment]
Now I'm getting this
![Screenshot from 2021-11-01 23-20-07](https://user-images.githubusercontent.com/5784951/139776227-da43d2d4-8dd7-4b4e-b219-06a56e0102b4.png)
:

**Comment by gglanzani** [comment]
+1, getting the same here

**Comment by normen** [comment]
> +1, getting the same here

Did you also try to upload a file?

Anyway, I can't connect either, I guess this is due to #51 - looks like it will be broken until both the new library is done and its integrated into whatscli. Closing this in favor of #51

**Comment by gglanzani** [comment]
@normen No, I didn't try to upload anything :)

**Comment by kurokirasama** [comment]
I haven't join the beta

**Comment by normen** [comment]
Even if you don't join the beta they still do changes on the servers 😄

**Comment by kurokirasama** [comment]
ok, sad... really looking forward for the fix... I've been looking for something like this for a while now, and was only able to use for like 30 min lol

**Comment by normen** [comment]
Imagine the fate of people who already got used to it 😬

**Comment by normen** [comment]
Looks like sending an old client version fixed one of the issues, ymmv. See release 1.0.11

**Comment by kurokirasama** [comment]
cool!! thanks, it's working good so far!
