### ISSUE TITLE
Message type not implemented

### ISSUE THREAD

**Issue by OrangeXarot** [normen/whatscli#58]
When I connect it starts spamming "message type not implemented" and then it crashes
(I am not in multi-device beta)

![2021-11-13_18-38](https://user-images.githubusercontent.com/43382695/141653549-c4351552-a56c-4028-9058-0f478f8cc4c9.png)

**Comment by normen** [comment]
Can you post the stack trace of the crash?

**Comment by OrangeXarot** [comment]
> Can you post the stack trace of the crash?

I'm sorry, I'm new at programming, what is a "stack trace"? and how can I find it to post it

**Comment by normen** [comment]
The funny text after the crash with the line numbers and cryptic words.

**Comment by OrangeXarot** [comment]
It doesn't say anything, it just crashes. Btw thanks for the patience

**Comment by OrangeXarot** [comment]
I solved it, the problem was that my terminal was not compatible with emojis and that made it crash, I changed terminal and now it works (:
