### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by bindev-bit** [normen/whatscli#59]
![Screen Shot 2021-11-17 at 10 00 31](https://user-images.githubusercontent.com/77034437/142127574-f3d0f29c-b545-4e52-83e7-5d4df1f78b47.png)

i have problem when i scan qr to login, i use whatsapp ios to scan.
Can anyone help me?

**Comment by DMaroo** [comment]
I am also facing the same problem. I am using `whatscli` on Arch linux and using WhatsApp on an Android device to scan the code.

**Comment by dvisan** [comment]
Experiencing the same issue on EndeavourOS using an iOS device to scan the code

**Comment by DMaroo** [comment]
Updating WhatsApp on my Android device worked for me.

**Comment by felixei** [comment]
Same Issue here. Possibly an issue with using the multi-device beta?

**Comment by lemagnific** [comment]
> Same Issue here. Possibly an issue with using the multi-device beta?

I have two computers using this app now. The first one was working pretty fine and I installed in another laptop, then the problem started when I joined multi-device beta, it seems to be a problem with multi-device beta. I removed my account from multi-device beta and it works on both devices, one at once.

**Comment by normen** [comment]
See #51 and #56
