### ISSUE TITLE
[Feature] notifications

### ISSUE THREAD

**Issue by normen** [normen/whatscli#6]
The app should allow for notifications and new message indicators.

**Comment by unixbhaskar** [comment]
No pop up please ..sound might alright...

**Comment by normen** [comment]
I'll only add this when it can be configured. And this is not a pony farm, no wishes granted here 😝

Am 18.11.2020 21:09 schrieb Bhaskar Chowdhury:

**Comment by normen** [comment]
0.8.7 adds support for notifications, a timeout (since last message sent) is used to determine if a notification for the current chat should appear.
