### ISSUE TITLE
Scanning the qr code does nothing

### ISSUE THREAD

**Issue by dnaik42** [normen/whatscli#60]
Whatsapp refuses to acknowledge the qr code even though I'm scanning it clearly. I tried switching terminal emulators (kitty to gnome-terminal) to see if it was a rendering issue with the code, but that didn't work either.

**Comment by normen** [comment]
I've seen it fail on terminals that are black on white by default. Other than that - hard to say whats the issue with solely anecdotal info.

**Comment by dnaik42** [comment]
Ok yeah changing the theme to white on black worked, thanks
