### ISSUE TITLE
can't see sent messages

### ISSUE THREAD

**Issue by kurokirasama** [normen/whatscli#74]
I know is a work in progress, but in whatsmeow version, I can send messages successfully, but I connot see them, they don't show up to me.

Also, the status says always offline.

**Comment by normen** [comment]
Yeah, "live" messages don't get received yet, though in theory the code is there, you might get that to work though. Status isn't implemented. Otherwise, yes, its a WIP, the branch was rather meant for people who might want to take a shot at finishing it before me 😘
