### ISSUE TITLE
Please fix this sih*

### ISSUE THREAD

**Issue by HaroonRehman** [normen/whatscli#77]
![image](https://user-images.githubusercontent.com/76829403/180051931-a66ad464-fc0d-49be-9418-fce6cada877d.png)

**Comment by MrDoode** [comment]
I have the same Problem. is there any way to generate a log, to get more info?

**Comment by normen** [comment]
> What the Shi*t this Repository is ? instead of solving the issue they just Closed the Issue as Completed WOW .

👍

**Comment by b3h3m0th** [comment]
Sorry for reactivating this absolutely inappropriate issue but unfortunately I'm having the same issue and I couldn't really find a solution anywhere. Btw this Repo looks amazing and I'd love to see the app running properly :D

**Comment by normen** [comment]
#72
