### ISSUE TITLE
Does not run on M1 MacBook Pro

### ISSUE THREAD

**Issue by larsinka** [normen/whatscli#83]
# Description

Programm does not run, produces weird output to terminal on OSX.

# Steps to reproduce

1. Use M1 Mac
2. ```$ brew install normen/tap/whatscli```
3. ```$ whatscli```

# Version

Platform: macOS Version 12.6 (Build 21G115), 64 bit, Little endian, wxMac

https://user-images.githubusercontent.com/62347791/198145483-31b03193-ddbc-4ca1-9c7d-87c4fac08b4e.mov

**Comment by normen** [comment]
See #72
