### ISSUE TITLE
installation on arch

### ISSUE THREAD

**Issue by liamannor** [normen/whatscli#85]
got this error code
panic: runtime error: invalid memory address or nil pointer dereference
                          [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5578f364815f]

                          goroutine 40 [running]:
                                                 github.com/Rhymen/go-whatsapp.(*Conn).Login(0x0, 0x0?)
                          	github.com/Rhymen/go-whatsapp@v0.1.2-0.20210615184944-2b8a3e9b8aa2/session.go:191 +0x7f
                                          github.com/normen/whatscli/messages.(*SessionManager).loginWithConnection(0xc0001ccb00, 0x0)
                                                         	github.com/normen/whatscli/messages/session_manager.go:234 +0x1d3
                                                    github.com/normen/whatscli/messages.(*SessionManager).runManager(0xc0001ccb00)
                                                     	github.com/normen/whatscli/messages/session_manager.go:71 +0x4e
                                          created by github.com/normen/whatscli/messages.(*SessionManager).StartManager
                                          	github.com/normen/whatscli/messages/session_manager.go:65 +0x6b

**Comment by AdhamNasr** [comment]
same issue, i think the repo is not being updated.

**Comment by normen** [comment]
see #72 and #51
