### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dims12** [normen/whatscli#89]
Cloned, did

    `make build`

got executable, ran it

   `./whatscli`

and it crashed with screen garbaged and

    `panic: runtime error: invalid memory address or nil pointer dereference`

How to fix?

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

```
# go version
go version go1.20 linux/amd64

```

**Comment by normen** [comment]
See #72 and #51
