### ISSUE TITLE
Panic: Runtime Error on Mac

### ISSUE THREAD

**Issue by riz-ahmed** [normen/whatscli#91]
Freshly installed package using either brew / building from source. Produces this error 

![image](https://user-images.githubusercontent.com/38962235/223837183-ccbd8c72-fdd5-4c4b-8666-d63f0afa245b.png)

my system configurations are as follows:
OS: MacOS 12.0.1 (Intel)
Terminal: tried both with iTerm as well as Alacritty

Can you please look into it. thanks!

**Comment by normen** [comment]
See #51 and #72
