### ISSUE TITLE
application crash after 1s

### ISSUE THREAD

**Issue by KarolPauk** [normen/whatscli#96]
I've built the program with _go build_   command, added whatscli executable file to /usr/bin. I've run the program with whatscli command. Program crashed after 0.5s or 1s from start and showed this: 
![Zrzut ekranu z 2023-06-14 16-37-04](https://github.com/normen/whatscli/assets/132209958/d959c9b6-84f9-40f7-8098-e47e5ee39257)

**Comment by normen** [comment]
Please look at the pinned issues.
