### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by b1ek** [normen/whatscli#97]
Last commit at this moment is ae25296b9d47087af72e561ce80a8382e9dbf7cc, which was 3 years ago, and last open PR is 1 year old.

Shouldn't there be some kind of message in README about it so another developer could pick it up?

**Comment by normen** [comment]
This is github, just fork or make a PR if I'm not working fast enough for you.

**Comment by b1ek** [comment]
> if I'm not working fast enough for you

seriously? you have went silent for 2 years and did nothing other than closing pressing issues with a half baked justification, instead of actually solving them and improving on your project. grow up already, you are not in 6th grade anymore. i won't reply any further

**Comment by normen** [comment]
> > if I'm not working fast enough for you
> 
> seriously? you have went silent for 2 years and did nothing other than closing pressing issues with a half baked justification, instead of actually solving them and improving on your project. grow up already, you are not in 6th grade anymore. i won't reply any further

Seriously? Are you _seriously_ suggesting that I have some kind of obligation to do work for you? Okay, heres your money back.
