### ISSUE TITLE
whatsmewo branch - Error reading from websocket: [websocket: close 1006 (abnormal closure): unexpected EOF]

### ISSUE THREAD

**Issue by C-0-S-M-1-N** [normen/whatscli#99]
after scanning the qr code ```Error reading from websocket: [websocket: close 1006 (abnormal closure): unexpected EOF]``` pops up in the panel. If i reran the program there is only the error without the qr code. I managed to find that if i remove the ```mdtest.db``` and ```messages.db``` files the qr code pops up again and after scanning the error comes right back up.

**Comment by normen** [comment]
mdtest.db? messages.db? It seems you're using the whatsmeow branch, which is not supposed to work.
